meson: Fix local build of the settings_gen taget
Currently local meson build fails with the following error:
"""
[343/700] Generating settings_manager_hpp with a custom command
FAILED: settings_manager.hpp
<...>/env/bin/python3 ../settings.py -i ../settings_example.yaml
<...>
ModuleNotFoundError: No module named 'sdbusplus'
"""
This is happening because 'settings_manager.mako.hpp' from the
'settings_gen' target refers to python modules from the external
'sdbusplus' project. Therefore in case of a local build it is
necessary to provide search path to the relevant sdbusplus subproject
folder. Fix this with the help of 'PYTHONPATH' environment variable.

Tested:
Both local meson build and Yocto build are finished successfully.

Change-Id: I8ec81edcdeb84c82a315937d3ed31be3dbaa1aa5
Signed-off-by: Konstantin Aladyshev <aladyshev22@gmail.com>